disableStartupPopups: false
customCommands:
  - key: "k"
    context: "files"
    prompts:
      - type: "input"
        title: "Add Commit Message"
        key: "Message"

    command: git commit -m "$(kontainer-commit-message){{ .Form.Message }}"
    subprocess: true
    description: "Custom commit message"
