"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format ="""
${custom.vpn}\
$all"""

[custom.vpn]
when = "test -f $HOME/.vpn_active"
style = "green"
format = "[\\[vpn\\]]($style)"
