{ pkgs, ... }:
with pkgs; [
  php83
  php83Extensions.zstd
  php83Extensions.zlib
  php83Extensions.zip
  php83Extensions.zend_test
  php83Extensions.yaml
  php83Extensions.xsl
  php83Extensions.xmlreader
  php83Extensions.xml
  php83Extensions.xdebug
  php83Extensions.wikidiff2
  php83Extensions.vld
  php83Extensions.uv
  php83Extensions.uuid
  php83Extensions.tokenizer
  php83Extensions.tidy
  php83Extensions.tideways
  php83Extensions.sysvshm
  php83Extensions.sysvsem
  php83Extensions.sysvmsg
  php83Extensions.swoole
  php83Extensions.ssh2
  php83Extensions.sqlsrv
  php83Extensions.sqlite3
  php83Extensions.spx
  php83Extensions.sodium
  php83Extensions.sockets
  php83Extensions.soap
  php83Extensions.snuffleupagus
  php83Extensions.snmp
  php83Extensions.smbclient
  php83Extensions.simplexml
  php83Extensions.shmop
  php83Extensions.session
  php83Extensions.rrd
  php83Extensions.relay
  php83Extensions.redis
  php83Extensions.readline
  php83Extensions.rdkafka
  php83Extensions.pspell
  php83Extensions.protobuf
  php83Extensions.posix
  php83Extensions.pinba
  php83Extensions.phalcon
  php83Extensions.pgsql
  php83Extensions.pdo_sqlsrv
  php83Extensions.pdo_sqlite
  php83Extensions.pdo_pgsql
  php83Extensions.pdo_odbc
  php83Extensions.pdo_oci
  php83Extensions.pdo_mysql
  php83Extensions.pdo_dblib
  php83Extensions.pdo
  php83Extensions.pdlib
  php83Extensions.pcov
  php83Extensions.pcntl
  php83Extensions.parallel
  php83Extensions.opentelemetry
  php83Extensions.openswoole
  php83Extensions.openssl-legacy
  php83Extensions.openssl
  php83Extensions.opcache
  php83Extensions.oci8
  php83Extensions.mysqlnd
  php83Extensions.mysqli
  php83Extensions.msgpack
  php83Extensions.mongodb
  php83Extensions.memprof
  php83Extensions.meminfo
  php83Extensions.memcached
  php83Extensions.memcache
  php83Extensions.mbstring
  php83Extensions.maxminddb
  php83Extensions.mailparse
  php83Extensions.luasandbox
  php83Extensions.ldap
  php83Extensions.ioncube-loader
  php83Extensions.intl
  php83Extensions.inotify
  php83Extensions.imap
  php83Extensions.imagick
  php83Extensions.igbinary
  php83Extensions.iconv
  php83Extensions.grpc
  php83Extensions.gnupg
  php83Extensions.gmp
  php83Extensions.gettext
  php83Extensions.gd
  php83Extensions.ftp
  php83Extensions.filter
  php83Extensions.fileinfo
  php83Extensions.ffi
  php83Extensions.exif
  php83Extensions.excimer
  php83Extensions.event
  php83Extensions.enchant
  php83Extensions.ds
  php83Extensions.dom
  php83Extensions.decimal
  php83Extensions.dba
  php83Extensions.datadog_trace
  php83Extensions.curl
  php83Extensions.ctype
  php83Extensions.couchbase
  php83Extensions.calendar
  php83Extensions.bz2
  php83Extensions.blackfire
  php83Extensions.bcmath
  php83Extensions.ast
  php83Extensions.apcu
  php83Extensions.amqp


]
