#!/usr/bin/env bash
# Generate per-monitor hyprlock.conf with scale compensation, then lock.
# Hyprlock does not auto-scale widgets per monitor scale factor, so
# fractionally-scaled outputs (e.g. eDP-1 at 1.5x) render visibly smaller
# than 1x outputs. This script emits one widget block per connected
# monitor with sizes multiplied by that monitor's scale.
#
# Works under both Hyprland and niri (detected via env vars).

set -euo pipefail

pidof hyprlock >/dev/null && exit 0

readonly OUT="${XDG_RUNTIME_DIR:-/tmp}/hyprlock.conf"
readonly THEME="${HOME}/.config/hypr/theme.conf"
readonly BG="${HOME}/.stubbe/src/wallpapers/ballet.jpg"

list_monitors() {
  if [ -n "${HYPRLAND_INSTANCE_SIGNATURE-}" ]; then
    hyprctl monitors -j | jq -r '.[] | "\(.name)\t\(.scale)"'
  elif [ -n "${NIRI_SOCKET-}" ]; then
    niri msg --json outputs \
      | jq -r 'to_entries[] | select(.value.logical != null)
               | "\(.key)\t\(.value.logical.scale)"'
  else
    echo "hyprlock.launch.sh: no Hyprland or niri session detected" >&2
    exit 1
  fi
}

scaled() { awk -v b="$1" -v s="$2" 'BEGIN{printf "%g", b*s}'; }

emit_widgets() {
  local mon="$1" s="$2"
  cat <<EOF

# === ${mon} (scale ${s}) ===

label {
  monitor = ${mon}
  text = \$TIME
  color = \$text
  font_size = $(scaled 90 "$s")
  font_family = \$font
  position = $(scaled -30 "$s"), 0
  halign = right
  valign = top
}

label {
  monitor = ${mon}
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = \$text
  font_size = $(scaled 25 "$s")
  font_family = \$font
  position = $(scaled -30 "$s"), $(scaled -150 "$s")
  halign = right
  valign = top
}

label {
  monitor = ${mon}
  text = \$USER
  color = \$text
  font_size = $(scaled 14 "$s")
  font_family = \$font
  position = 0, $(scaled 80 "$s")
  halign = center
  valign = center
}

input-field {
  monitor = ${mon}
  size = $(scaled 300 "$s"), $(scaled 60 "$s")
  outline_thickness = $(scaled 4 "$s")
  dots_size = 0.2
  dots_spacing = 0.2
  dots_center = true
  outer_color = \$accent
  inner_color = \$surface0
  font_color = \$text
  font_family = \$font
  fade_on_empty = false
  placeholder_text = <span foreground="##\$textAlpha"><i>󰌾 Logged in as </i><span foreground="##\$accentAlpha">\$USER</span></span>
  hide_input = false
  check_color = \$accent
  fail_color = \$red
  fail_text = <i>\$FAIL <b>(\$ATTEMPTS)</b></i>
  capslock_color = \$yellow
  position = 0, $(scaled -47 "$s")
  halign = center
  valign = center
}
EOF
}

{
  cat <<EOF
# Auto-generated by hyprlock.launch.sh — do not edit.
source = ${THEME}

\$accent = \$mauve
\$accentAlpha = \$mauveAlpha
\$font = JetBrainsMono Nerd Font

general {
  no_fade_in = true
  no_fade_out = true
  ignore_empty_input = true
  enable_fingerprint = false
  hide_cursor = true
}

animations {
  enabled = false
}

background {
  monitor =
  path = ${BG}
  blur_passes = 0
  color = \$base
}
EOF

  while IFS=$'\t' read -r name scale; do
    [ -z "$name" ] && continue
    emit_widgets "$name" "$scale"
  done < <(list_monitors)
} > "$OUT"

exec hyprlock --config "$OUT"
