{ pkgs, config, ... }:
with pkgs; [
  hyprland
  hyprlock
  hyprshot
  hyprlang
  hyprkeys
  hypridle
  hyprpaper
  hyprsunset
  hyprpicker
  hyprcursor
  hyprpolkitagent
  hyprutils
  hyprprop
  wlprop
  hyprsysteminfo
  hyprwayland-scanner
  wayland-scanner
  wayland-utils
  xwayland
  waybar
  swaynotificationcenter
  rofi
  xdg-desktop-portal
  xdg-desktop-portal-hyprland
  xdg-desktop-portal-wlr
  wl-clip-persist
]
