#!/bin/bash


alias l='ls -lF'   #size,show type,human readable
alias la='ls -lAF' #long list,show almost all,show type,human readable
alias lr='ls -tRF' #sorted by date,recursive,show type,human readable
alias ll='ls -l'    #long list
alias ff='find . -type f -name'
alias h='history'
alias hgrep="fc -El 0 | grep"
alias p='ps -f'
alias sortnr='sort -n -r'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
