#!/bin/bash


alias la='ls -laF'
alias ff='find . -type f -name'
alias h='history'
alias hgrep="fc -El 0 | grep"
alias p='ps -f'
alias sortnr='sort -n -r'
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias pbcopy='xclip -selection clipboard'
alias pbpaste='xclip -selection clipboard -o'
alias sd="clear && cd \$(find ~/git -maxdepth 3 -mindepth 1 -type d -exec test -d '{}/.git' \; -print 2>/dev/null | fzf)"
alias gzcat="gzip -dc"
