#!/bin/bash
STBZSHSOURCES=(
  "paths"
  "funcs"
  "aliases"
  "plugins"
  "settings"
  "secrets"
)
if [ -d "$HOME/.stubbe" ]; then
    STBDIR="$HOME/.stubbe/src/zsh"
    for SZP in "${STBZSHSOURCES[@]}"; do
        if [ -f "$STBDIR/$SZP" ]; then
            source "$STBDIR/$SZP"
        fi
    done
fi
