#!/usr/bin/env zsh

autoload -Uz compinit
autoload -Uz add-zsh-hook

STBZSHSOURCES=(
  "paths"
  "sysfuncs"
  "updates"
  "funcs"
  "aliases"
  "secrets"
  "plugins"
  "fpaths"
  "settings"
)

if [ -d "$HOME/.stubbe" ]; then
  STBDIR="$HOME/.stubbe/src/zsh"
  for SZP in "${STBZSHSOURCES[@]}"; do
    if [ -f "$STBDIR/$SZP" ]; then
      source "$STBDIR/$SZP"
    fi
  done
fi
