#!/usr/bin/env zsh

if ! is_file "$STBDIR/update_flag"; then
  date -d "+1 days" +%s > "$STBDIR/update_flag"
fi

STB_TIME_TO_UPDATE=$(cat $STBDIR/update_flag)
STB_TIME_NOW=$(date +%s)

if [[ "$STB_TIME_NOW" -lt "$STB_TIME_TO_UPDATE" ]]; then
  STB_SHOULD_UPDATE=false
else
  STB_SHOULD_UPDATE=true
  truncate -s 0 "$STBDIR/update_flag"
  date -d "+1 days" +%s > "$STBDIR/update_flag"
fi

function source_github_plugins() {
  local -a args=("$@")
  local parent_dir=${args[-1]}
  local urls=("${args[@]:0:${#args[@]}-1}")
  mkdir -p "$parent_dir"
  for url in $urls; do
    if [[ ! "$url" =~ ^https?: ]]; then
      url="https://github.com/$url"
    fi
    local repo="${url:t:r}"
    local target="$parent_dir/$repo"
    if ! is_directory "$target"; then
      git clone "$url" "$target" > /dev/null
    elif [[ $STB_SHOULD_UPDATE == "true" ]]; then
      git -C "$target" pull --force > /dev/null
    fi
    local plugin_files=(${target}/*.plugin.zsh)
    for plugin_file in $plugin_files; do
      if [[ -f "$plugin_file" ]]; then
        source "$plugin_file"
      fi
    done
  done
}
