#!/usr/bin/env zsh

# SHELL THEME
if ! is_binary "/usr/local/bin/starship"; then
  curl -sS https://starship.rs/install.sh | sh
fi

STUBBE_ZSH_PLUGS_DIR="$HOME/.stubbe/src/zsh/plugins.d"

# FZF-TAB
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/fzf-tab"; then
  git clone "https://github.com/Aloxaf/fzf-tab.git" "$STUBBE_ZSH_PLUGS_DIR/fzf-tab"
fi
source "$STUBBE_ZSH_PLUGS_DIR/fzf-tab/fzf-tab.plugin.zsh"

# AUTOSUGGESTIONS
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions"; then
  git clone "https://github.com/zsh-users/zsh-autosuggestions.git" "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions"
fi
source "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"

# AUTOHIGHLIGHT
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/fast-syntax-highlighting"; then
  git clone "https://github.com/zdharma/fast-syntax-highlighting.git" "$STUBBE_ZSH_PLUGS_DIR/fast-syntax-highlighting"
fi

# LARAVEL
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/zsh-artisan"; then
  git clone "https://github.com/jessarcher/zsh-artisan.git" "$STUBBE_ZSH_PLUGS_DIR/zsh-artisan"
fi
if is_binary compdef; then
  source "$STUBBE_ZSH_PLUGS_DIR/zsh-artisan/artisan.plugin.zsh"
fi

# VIM-MODE
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/zsh-vim-mode"; then
  git clone "https://github.com/softmoth/zsh-vim-mode.git" "$STUBBE_ZSH_PLUGS_DIR/zsh-vim-mode"
fi
source "$STUBBE_ZSH_PLUGS_DIR/zsh-vim-mode/zsh-vim-mode.plugin.zsh"
