#!/bin/zsh

STUBBE_ZSH_PLUGS_DIR="$STUBBE_CONFIG_ROOT/src/zsh/plugins.d"

if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/zsh-syntax-highlighting"; then
  git clone "https://github.com/zsh-users/zsh-syntax-highlighting.git" "$STUBBE_ZSH_PLUGS_DIR/zsh-syntax-highlighting"
fi
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions"; then
  git clone "https://github.com/zsh-users/zsh-autosuggestions.git" "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions"
fi
if ! is_directory "$STUBBE_ZSH_PLUGS_DIR/zsh-autopair"; then
  git clone "https://github.com/hlissner/zsh-autopair.git" "$STUBBE_ZSH_PLUGS_DIR/zsh-autopair"
fi

if ! is_binary "/usr/local/bin/starship"; then
  curl -sS https://starship.rs/install.sh | sh
fi

if ! is_binary zinit; then
  bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
  source "$HOME/.zshrc"
  zinit self-update
fi

if is_file "$STUBBE_ZSH_PLUGS_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"; then
  source "$STUBBE_ZSH_PLUGS_DIR/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi
if is_file "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"; then
  source "$STUBBE_ZSH_PLUGS_DIR/zsh-autosuggestions/zsh-autosuggestions.zsh"
fi
if is_file "$STUBBE_ZSH_PLUGS_DIR/zsh-autopair/zsh-autopair.zsh"; then
  source "$STUBBE_ZSH_PLUGS_DIR/zsh-autopair/zsh-autopair.zsh"
fi

