#!/bin/bash

# PLACE SECRETS LIKE PASSWORDS HERE
function get_secrets {
  TMPDIR=$(mktemp -d)
  git clone --depth=1 git@git.stubbe.dev:snippets/1.git "$TMPDIR" --quiet
  source "$TMPDIR"/SECRET
  rm -rf "$TMPDIR"
}

function edit_secrets {
  TMPDIR=$(mktemp -d)
  git clone --depth=1 git@git.stubbe.dev:snippets/1.git "$TMPDIR" --quiet
  vim "$TMPDIR"/SECRET
}
