#!/bin/bash
# PLACE SECRETS LIKE PASSWORDS HERE
function get_secrets {
  TMPDIR=$(mktemp -d)
  git clone --depth=1 git@gist.github.com:9638e3ef68aa79aeec9a7021a23bbb73.git "$TMPDIR" --quiet
  source "$TMPDIR"/SECRET;
  rm -rf "$TMPDIR"
}

