#!/bin/bash
# PLACE SECRETS LIKE PASSWORDS HERE

if is_binary openvpn3; then
	function cvpn {
		ACTIVE_SESSIONS=$(openvpn3 sessions-list | grep -i 'path' | awk '{p=index($0, ":");print $2}')
		if ((${#ACTIVE_SESSIONS[@]})); then
			echo "Disconnecting from VPN..."
			for instance in $ACTIVE_SESSIONS; do
				openvpn3 session-manage --disconnect --session-path ${instance}
			done
		else
			echo "Connecting to VPN..."
			openvpn3 session-start --config ~/.ssh/client.ovpn
		fi
	}
fi

function exssh {

	if [ $# -eq 0 ]; then
		echo "Please provide the platform as a second argument: "
		echo "TheSocialDigits:           tsd"
		echo "StubbeDev:                 stb"
		echo "WooCommerce:               wp"
		echo "Magento 1:                 m1"
		echo "Magento 2:                 m2"
		echo "Presta 16:                 p16"
		echo "Presta 17:                 p17"
		echo "Shopware 6:                sw"
	else
		case "$1" in
		tsd | stb)
			if [ "$1" = "tsd" ]; then
				ssh abs@10.0.1.109 -i ~/.ssh/clerk_dev
			elif [ "$1" = "stb" ]; then
				ssh stubbe@78.141.213.187 -i ~/.ssh/stubbe_dev
			fi
			exit
			;;
		*)
			get_secret_gist
			if [ "$1" = "m2" ]; then
				sshpass -p "$DEVPASS" ssh $DEVNAME@65.20.115.65
			elif [ "$1" = "m1" ]; then
				sshpass -p "$DEVPASS" ssh $DEVNAME@70.34.197.144
			elif [ "$1" = "p16" ]; then
				sshpass -p "$DEVPASS" ssh $DEVNAME@70.34.204.36
			elif [ "$1" = "p17" ]; then
				sshpass -p "$DEVPASS" ssh $DEVNAME@70.34.203.120
			elif [ "$1" = "wp" ]; then
				sshpass -p "$DEVPASS" ssh $DEVNAME@70.34.200.87
			elif [ "$1" = "sw" ]; then
				sshpass -p "$DEVPASS" ssh $DEVNAME@70.34.205.147
			fi
			exit
			;;
		esac
	fi

}

function get_secret_gist {
	# GET PASSWORD REMOTELY
	# FROM PRIVATE GIST
	TMPDIR=$(mktemp -d)
	git clone --depth=1 git@gist.github.com:9638e3ef68aa79aeec9a7021a23bbb73.git $TMPDIR --quiet
	DEVNAME=$(sed -n "1{p;q;}" $TMPDIR/DEVPASS)
	DEVPASS=$(sed -n "2{p;q;}" $TMPDIR/DEVPASS)
	rm -rf $TMPDIR
}
