#!/bin/zsh

autoload -U compinit
compinit

HYPHEN_INSENSITIVE=false
DISABLE_AUTO_TITLE=true
ENABLE_CORRECTION=true
VIM_MODE_NO_DEFAULT_BINDINGS=true
HISTFILE=$STBDIR/history
HISTTIMEFORMAT="[%F %T] "
SAVEHIST=10000
HISTSIZE=10000
setopt APPEND_HISTORY
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt HIST_IGNORE_ALL_DUPS

# FOR CLIPBOARD STUFF
export DISPLAY=:0

if is_binary docker; then
  export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/docker.sock
fi

if is_binary zoxide; then
  eval "$(zoxide init zsh)"
fi

# if is_binary setxkbmap; then
#   setxkbmap -option caps:escape
# fi

if is_binary starship; then
  export STARSHIP_CONFIG="$HOME/.stubbe/src/starship/starship.toml"
  eval "$(starship init zsh)"
fi

