#!/usr/bin/env zsh

if ! is_file "$STBDIR/update_flag"; then
  date -d "+1 days" +%s > "$STBDIR/update_flag"
fi

STB_TIME_TO_UPDATE=$(cat $STBDIR/update_flag)
STB_TIME_NOW=$(date +%s)

if [[ "$STB_TIME_NOW" -lt "$STB_TIME_TO_UPDATE" ]]; then
  STB_SHOULD_UPDATE=false
else
  STB_SHOULD_UPDATE=true
  truncate -s 0 "$STBDIR/update_flag"
  date -d "+1 days" +%s > "$STBDIR/update_flag"
fi

