#!/usr/bin/env zsh

function _fzf_tmux_project_picker {
    fzf-tmux-project-picker
}

function _fzf_project_picker {
    fzf-project-picker
}

function _fzf_tmux_session_picker {
    fzf-tmux-session-picker
}

zle -N _fzf_tmux_project_picker
zle -N _fzf_project_picker
zle -N _fzf_tmux_session_picker

bindkey "^[f" _fzf_tmux_project_picker
bindkey "^[F" _fzf_project_picker
bindkey "^[d" _fzf_tmux_session_picker

