# The local new-tab / new-window page, and its registration with srv.
#
# Browsers refuse to inject extension content scripts into the built-in new tab
# page (about:newtab, chrome://newtab) — that is why Tridactyl and SurfingKeys
# show a "can't run here" banner there. Pointing both browsers at this page
# instead avoids it. It is served over https by srv rather than file://, because
# Tridactyl's `set newtab` double-opens file:// URLs (tridactyl#530) and one
# https URL works for both browsers.
{ inputs, ... }:
{
  flake.modules.homeManager.newtab =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      c = pkgs.stubbe.withHash;
      # A stable real directory, not a store path, so `srv add` registers it
      # once and content updates land without re-running srv.
      root = "${config.xdg.dataHome}/stubbedev/newtab";
      # ''$ below escapes JS template literals — only the nix ${…} are ours.
      page = pkgs.writeText "newtab.html" ''
        <!DOCTYPE html>
        <!-- Minimal local new-tab / new-window page, generated by modules/browsers/newtab.nix. -->
        <html lang="en">
        <head>
          <meta charset="utf-8" />
          <title>New Tab</title>
          <style>
            :root { color-scheme: dark; }
            html, body {
              margin: 0;
              height: 100%;
              background: ${c.base};
              color: ${c.text};
              font-family: ui-monospace, "JetBrains Mono", "SFMono-Regular", monospace;
            }
            body {
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              gap: 0.25rem;
            }
            #time { font-size: 5rem; font-weight: 600; letter-spacing: 0.04em; }
            #date { font-size: 1.2rem; color: ${c.overlay2}; }
          </style>
        </head>
        <body tabindex="-1">
          <div id="time">--:--</div>
          <div id="date"></div>
          <script>
            const pad = (n) => String(n).padStart(2, "0");

            class Clock {
              // Private fields — `this` resolves to the instance inside methods
              // because they are real methods called as `clock.tick()`.
              #timeEl = document.getElementById("time");
              #dateEl = document.getElementById("date");
              #lastTime = "";
              #lastDate = "";

              tick() {
                const now = new Date();

                const time = `''${pad(now.getHours())}:''${pad(now.getMinutes())}`;
                if (time !== this.#lastTime) {
                  this.#lastTime = time;
                  this.#timeEl.textContent = time;
                }

                const date = now.toLocaleDateString(undefined, {
                  weekday: "long",
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                });
                if (date !== this.#lastDate) {
                  this.#lastDate = date;
                  this.#dateEl.textContent = date;
                }
              }
            }

            const clock = new Clock();
            clock.tick();
            // Arrow wrapper keeps the call form `clock.tick()`, so `this` stays
            // the instance — `setInterval(clock.tick, …)` would detach it.
            setInterval(() => clock.tick(), 1000);

            // Pull focus to the page. Browsers park the cursor in the address bar
            // when this loads as the new-tab / home page (Tridactyl's `set newtab`
            // redirects from about:newtab, which is urlbar-focused). A focusable
            // <body> plus an explicit focus() after load takes it back.
            addEventListener("load", () => {
              window.focus();
              document.body.focus();
            });
          </script>
        </body>
        </html>
      '';
      srvBin = lib.getExe' inputs.srv.packages.${pkgs.stdenv.hostPlatform.system}.srv "srv";
    in
    lib.mkIf config.features.browsers {
      # Only the static root is installed here; registering it is the setup
      # below. Ordered after linkGeneration so home-manager's symlink cleanup
      # cannot remove the copied file.
      stubbe.mutable."${lib.removePrefix "${config.home.homeDirectory}/" root}/index.html" = {
        method = "copy";
        source = page;
      };

      # Register the site with srv so it is served at https://start.local. srv's
      # site state is Docker-backed and lives outside Nix, so this is a
      # best-effort idempotent registration: it skips when the site is already
      # registered or srv is not installed yet, and never aborts activation.
      stubbe.setup.srvNewtab = lib.mkIf config.features.srv {
        after = [ "mutableFiles" ];
        script = ''
          # srv shells out to docker (site containers) and sudo (DNS); the
          # activation runs with a minimal PATH, so make those reachable —
          # covering NixOS (/run/…) and a standalone-HM distro (/usr/bin).
          export PATH="/run/wrappers/bin:/run/current-system/sw/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

          # `srv install` (Docker, Traefik, mkcert) is a one-time manual step
          # that lives outside Nix. Skip quietly until it has run — the next
          # switch retries — and never abort the activation.
          if [ ! -d "$HOME/.config/srv" ]; then
            echo "srv-newtab: srv not installed (run 'srv install'); skipping."
            exit 0
          fi

          # Register once; `srv add` also starts it. Its docker-compose progress
          # goes to /dev/null, stderr keeps real errors.
          if ! ${srvBin} info start-local >/dev/null 2>&1; then
            ${srvBin} add ${lib.escapeShellArg root} \
              --domain start.local --name start-local --local </dev/null >/dev/null \
              || echo "srv-newtab: 'srv add' failed; will retry next switch." >&2
          fi

          # Ensure it is running — an earlier run may have registered the site
          # while Docker was unreachable, leaving it stopped.
          ${srvBin} start start-local </dev/null >/dev/null 2>&1 || true
        '';
      };
    };
}
