# Browsers refuse to inject extension content scripts into the built-in new tab
# page (about:newtab, chrome://newtab) — that is why Tridactyl and SurfingKeys
# show a "can't run here" banner there. Pointing both browsers at this page
{ inputs, ... }:
{
  flake.modules.homeManager.newtab =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    let
      c = pkgs.stubbe.withHash;
      root = "${config.xdg.dataHome}/stubbedev/newtab";
      # ''$ below escapes JS template literals — only the nix ${…} are ours.
      page = pkgs.writeText "newtab.html" ''
        <!DOCTYPE html>
        <!-- Minimal local new-tab / new-window page, generated by modules/browsers/newtab.nix. -->
        <html lang="en">
        <head>
          <meta charset="utf-8" />
          <title>New Tab</title>
          <style>
            :root { color-scheme: dark; }
            html, body {
              margin: 0;
              height: 100%;
              background: ${c.base};
              color: ${c.text};
              font-family: ui-monospace, "JetBrains Mono", "SFMono-Regular", monospace;
            }
            body {
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              gap: 0.25rem;
            }
            #time { font-size: 5rem; font-weight: 600; letter-spacing: 0.04em; }
            #date { font-size: 1.2rem; color: ${c.overlay2}; }
          </style>
        </head>
        <body tabindex="-1">
          <div id="time">--:--</div>
          <div id="date"></div>
          <script>
            const pad = (n) => String(n).padStart(2, "0");

            class Clock {
              // Private fields — `this` resolves to the instance inside methods
              // because they are real methods called as `clock.tick()`.
              #timeEl = document.getElementById("time");
              #dateEl = document.getElementById("date");
              #lastTime = "";
              #lastDate = "";

              tick() {
                const now = new Date();

                const time = `''${pad(now.getHours())}:''${pad(now.getMinutes())}`;
                if (time !== this.#lastTime) {
                  this.#lastTime = time;
                  this.#timeEl.textContent = time;
                }

                const date = now.toLocaleDateString(undefined, {
                  weekday: "long",
                  year: "numeric",
                  month: "long",
                  day: "numeric",
                });
                if (date !== this.#lastDate) {
                  this.#lastDate = date;
                  this.#dateEl.textContent = date;
                }
              }
            }

            const clock = new Clock();
            clock.tick();
            // Arrow wrapper keeps the call form `clock.tick()`, so `this` stays
            // the instance — `setInterval(clock.tick, …)` would detach it.
            setInterval(() => clock.tick(), 1000);

            // Pull focus to the page. Browsers park the cursor in the address bar
            // when this loads as the new-tab / home page (Tridactyl's `set newtab`
            // redirects from about:newtab, which is urlbar-focused). A focusable
            // <body> plus an explicit focus() after load takes it back.
            addEventListener("load", () => {
              window.focus();
              document.body.focus();
            });
          </script>
        </body>
        </html>
      '';
      srvBin = lib.getExe' inputs.srv.packages.${pkgs.stdenv.hostPlatform.system}.srv "srv";
    in
    lib.mkIf config.features.browsers {
      stubbe.mutable."${lib.removePrefix "${config.home.homeDirectory}/" root}/index.html" = {
        method = "copy";
        source = page;
      };

      stubbe.setup.srvNewtab = lib.mkIf config.features.srv {
        after = [ "mutableFiles" ];
        script = ''
          export PATH="/run/wrappers/bin:/run/current-system/sw/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:$PATH"

          if [ ! -d "$HOME/.config/srv" ]; then
            echo "srv-newtab: srv not installed (run 'srv install'); skipping."
            exit 0
          fi

          if ! ${srvBin} info start-local >/dev/null 2>&1; then
            ${srvBin} add ${lib.escapeShellArg root} \
              --domain start.local --name start-local --local </dev/null >/dev/null \
              || echo "srv-newtab: 'srv add' failed; will retry next switch." >&2
          fi

          ${srvBin} start start-local </dev/null >/dev/null 2>&1 || true
        '';
      };
    };
}
