-- Hyprland Lua config (0.55+). Replaces the old sourced .conf files.
-- Dynamic, Nix-derived values (cursor theme, NVIDIA env, hy3 plugin path)
-- live in nix.lua, generated by modules/home/xdg/hypr.nix.
require("nix")

local scripts = "/home/stubbe/.stubbe/src/hypr/scripts"
local shared = "/home/stubbe/.stubbe/src/_shared/scripts"

-- Catppuccin Mocha (only the shades referenced below).
local mauve = "rgb(cba6f7)"
local red = "rgb(f38ba8)"
local crust = "rgb(11111b)"
local surface0 = "rgb(313244)"
local text = "rgb(cdd6f4)"
local subtext0 = "rgb(a6adc8)"

------------------------------------------------------------------- ENV
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XDG_SESSION_DESKTOP", "Hyprland")
-- PATH, XDG_DATA_DIRS, XCURSOR_THEME, XCURSOR_SIZE come from Home Manager
-- session variables / NixOS environment.sessionVariables (cursor mirrored
-- in nix.lua for non-NixOS session managers).
hl.env("GDK_BACKEND", "wayland")
hl.env("GTK_USE_PORTAL", "0")
hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_STYLE_OVERRIDE", "kvantum")
hl.env("COLOR_SCHEME", "prefer-dark")
hl.env("ELECTRON_OZONE_PLATFORM_HINT", "auto")
hl.env("MOZ_ENABLE_WAYLAND", "1")
hl.env("TERMINAL", "alacritty")

--------------------------------------------------------------- MONITORS
hl.monitor({ output = "", mode = "highres", position = "auto", scale = "1" })
hl.monitor({ output = "eDP-1", mode = "preferred", position = "auto", scale = "1.5" })
hl.monitor({ output = "desc:LG Electronics LG HDR WQHD 207NTXRAJ498", mode = "preferred", position = "auto", scale = "1" })
hl.monitor({ output = "desc:LG Electronics LG HDR 4K 0x00016261", mode = "preferred", position = "auto", scale = "1.5" })

----------------------------------------------------------------- CONFIG
hl.config({
    general = {
        layout = "hy3",
        gaps_workspaces = 0,
        gaps_in = 0,
        gaps_out = 0,
        hover_icon_on_border = false,
        col = {
            inactive_border = crust,
            nogroup_border = crust,
            active_border = mauve,
            nogroup_border_active = mauve,
        },
    },

    dwindle = {
        preserve_split = true,
    },

    master = {
        new_status = "slave",
        orientation = "center",
    },

    ecosystem = {
        no_update_news = true,
        no_donation_nag = true,
    },

    decoration = {
        blur = {
            enabled = false,
        },
    },

    animations = {
        enabled = false,
    },

    input = {
        repeat_rate = 50,
        repeat_delay = 300,
        force_no_accel = true,
        kb_layout = "us,dk,es",
        kb_options = "grp:toggle",
    },

    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        focus_on_activate = false,
        -- HM activation hook reloads explicitly
        -- (modules/activation/_non-privileged/reload-hyprland.nix) so it can
        -- preserve focused workspace across multi-monitor reload.
        disable_autoreload = true,
    },

    xwayland = {
        force_zero_scaling = true,
    },
})

-- hy3 plugin config. Plugin itself is loaded in nix.lua via hl.plugin.load.
-- Guarded on hl.plugin.hy3: plugin.* config keys only exist once the plugin
-- is loaded, and hl.config errors on unknown keys, so configure only after
-- the plugin registered itself (per the official Hyprland Lua example).
-- Tab color keys were renamed in hy3 0.55 (col.active -> active, etc).
if hl.plugin.hy3 ~= nil then
    hl.config({
        plugin = {
            hy3 = {
                node_collapse_policy = 2,
                tabs = {
                    height = 15,
                    padding = 5,
                    render_text = true,
                    text_center = false,
                    text_height = 8,
                    text_padding = 3,
                    colors = {
                        active = mauve,
                        active_text = text,
                        urgent = red,
                        urgent_text = text,
                        inactive = surface0,
                        inactive_text = subtext0,
                    },
                },
                autotile = {
                    enable = true,
                    ephemeral_groups = true,
                    trigger_width = 600,
                    trigger_height = 0,
                    workspaces = "all",
                },
            },
        },
    })
end

----------------------------------------------------------------- DEVICE
-- Per-device block instead of global input.touchpad{}. Global touchpad
-- settings sometimes fail to re-apply to the i2c-hid touchpad after
-- `hyprctl reload` (triggered on dock unplug by scripts/monitor.toggle.sh),
-- leaving two-finger scroll dead until a Hyprland restart. A device block
-- fully overrides input.touchpad{} (hyprwm/Hyprland#2895), so scroll options
-- must be set here or libinput falls back to its own defaults.
hl.device({
    name = "snsl0028:00-2c2f:0028-touchpad",
    middle_button_emulation = true,
    clickfinger_behavior = true,
    drag_lock = true,
    tap_to_click = true,
    natural_scroll = false,
    scroll_method = "2fg",
    scroll_factor = 1.0,
    disable_while_typing = false,
})

-------------------------------------------------------------- AUTOSTART
hl.on("hyprland.start", function()
    -- Update D-Bus and systemd environment. QT_QPA_PLATFORMTHEME and
    -- QT_STYLE_OVERRIDE are intentionally NOT imported to systemd to keep them
    -- from persisting and breaking a later KDE Plasma login.
    hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_THEME XDG_DATA_DIRS SSH_AUTH_SOCK HYPRLAND_INSTANCE_SIGNATURE")
    hl.exec_cmd("compositor-session hyprland")
    hl.exec_cmd("hyprctl setcursor $XCURSOR_THEME $XCURSOR_SIZE")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("wl-paste --watch cliphist store")
    hl.exec_cmd("wl-clip-persist --clipboard regular")
    hl.exec_cmd("blueman-applet")
    hl.exec_cmd("nm-applet --indicator")
    hl.exec_cmd(scripts .. "/hy3.tiling.sh")
    hl.exec_cmd(scripts .. "/jetbrains.popup.resize.sh")
    hl.exec_cmd(scripts .. "/monitor.toggle.sh daemon")
end)

-------------------------------------------------------------- KEYBINDINGS
local mod = "SUPER"

-- hy3 is the only layout. These dispatch hy3's custom commands; they access
-- hl.plugin.hy3 at keypress time (the plugin is loaded by then) to avoid any
-- config-eval ordering races. resize_active uses the native dispatcher.
local function hy3_focus(d)
    return function() hl.dispatch(hl.plugin.hy3.move_focus(d)) end
end
-- Move the focused window, but skip the dispatch if it is already at the
-- workspace edge in that direction. hy3:movewindow at an edge collapses/creates
-- a group and shifts sizes by group_inset, shrinking a neighbour — the old
-- wrapper.movewindow.sh guarded against this the same way.
local function hy3_move(d)
    return function()
        local f = hl.get_active_window()
        if not f then return end
        local wins = hl.get_workspace_windows(f.workspace)
        local edge = false
        if d == "l" then
            local m = f.at.x
            for _, w in ipairs(wins) do if w.at.x < m then m = w.at.x end end
            edge = f.at.x <= m
        elseif d == "r" then
            local m = f.at.x
            for _, w in ipairs(wins) do if w.at.x > m then m = w.at.x end end
            edge = f.at.x >= m
        elseif d == "u" then
            local m = f.at.y
            for _, w in ipairs(wins) do if w.at.y < m then m = w.at.y end end
            edge = f.at.y <= m
        elseif d == "d" then
            local m = f.at.y
            for _, w in ipairs(wins) do if w.at.y > m then m = w.at.y end end
            edge = f.at.y >= m
        end
        if not edge then hl.dispatch(hl.plugin.hy3.move_window(d)) end
    end
end
local function hy3_to_ws(n)
    return function() hl.dispatch(hl.plugin.hy3.move_to_workspace(tostring(n))) end
end
local function hy3_kill()
    hl.dispatch(hl.plugin.hy3.kill_active())
end
local function resize_active(dx, dy)
    return hl.dsp.window.resize({ x = dx, y = dy, relative = true })
end

-- Launchers.
hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("alacritty"))
hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd("pcmanfm"))
hl.bind(mod .. " + SPACE", hl.dsp.exec_cmd("rofi -drun-reload-desktop-cache -drun-use-desktop-cache -show drun -location 0 -width 60"))
hl.bind(mod .. " + SHIFT + SPACE", hl.dsp.exec_cmd([[rofi -show combi -combi-modes "run" -modes combi -run-command "/home/stubbe/.stubbe/src/hypr/scripts/rofi.run.sh {cmd}" -location 0 -width 60]]))
hl.bind(mod .. " + CTRL + SPACE", hl.dsp.exec_cmd([[rofi -show combi -combi-modes "window" -modes combi]]))
hl.bind("SHIFT + Print", hl.dsp.exec_cmd("pgrep -x grim >/dev/null || hyprshot -m active -m output --clipboard-only"))
hl.bind("Print", hl.dsp.exec_cmd("pgrep -x slurp >/dev/null || hyprshot -m region --clipboard-only"))
hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("screen-record toggle"))
hl.bind(mod .. " + V", hl.dsp.exec_cmd([[cliphist list | rofi -dmenu | cliphist decode | wl-copy && wtype -M ctrl v && notify-send "Pasted selection"]]))
hl.bind(mod .. " + C", hl.dsp.exec_cmd([[wl-copy "$(wl-paste -p)" && notify-send "Copied selection"]]))
hl.bind(mod .. " + M", hl.dsp.exec_cmd("mail-open"))

-- General.
hl.bind(mod .. " + SHIFT + Q", hy3_kill)
hl.bind(mod .. " + F", hl.dsp.window.fullscreen())
hl.bind(mod .. " + T", hl.dsp.window.float({ action = "toggle" }))
hl.bind(mod .. " + escape", hl.dsp.exec_cmd(shared .. "/hyprlock.launch.sh"))
hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
hl.bind(mod .. " + delete", hl.dsp.exit())

-- Window focus / movement (hy3).
hl.bind(mod .. " + left", hy3_focus("l"))
hl.bind(mod .. " + right", hy3_focus("r"))
hl.bind(mod .. " + up", hy3_focus("u"))
hl.bind(mod .. " + down", hy3_focus("d"))

hl.bind(mod .. " + SHIFT + left", hy3_move("l"))
hl.bind(mod .. " + SHIFT + right", hy3_move("r"))
hl.bind(mod .. " + SHIFT + up", hy3_move("u"))
hl.bind(mod .. " + SHIFT + down", hy3_move("d"))

hl.bind(mod .. " + CTRL + left", resize_active(-50, 0))
hl.bind(mod .. " + CTRL + right", resize_active(50, 0))
hl.bind(mod .. " + CTRL + up", resize_active(0, -50))
hl.bind(mod .. " + CTRL + down", resize_active(0, 50))

-- Focus cycling.
hl.bind(mod .. " + mouse_down", hy3_focus("r"))
hl.bind(mod .. " + mouse_up", hy3_focus("l"))
hl.bind(mod .. " + bracketright", hy3_focus("r"))
hl.bind(mod .. " + bracketleft", hy3_focus("l"))

-- Workspace scrolling (native relative workspace switch).
hl.bind(mod .. " + SHIFT + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + mouse_up", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + SHIFT + bracketright", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + bracketleft", hl.dsp.focus({ workspace = "e-1" }))
hl.bind(mod .. " + Tab", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mod .. " + SHIFT + Tab", hl.dsp.focus({ workspace = "e-1" }))

-- Workspace switch (native) + layout-aware move-to-workspace.
for i = 1, 10 do
    local key = i % 10
    hl.bind(mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
    hl.bind(mod .. " + SHIFT + " .. key, hy3_to_ws(i))
end

-- Resize submap.
hl.bind(mod .. " + R", hl.dsp.submap("resize_mode"))
hl.define_submap("resize_mode", function()
    hl.bind("right", resize_active(10, 0), { repeating = true })
    hl.bind("left", resize_active(-10, 0), { repeating = true })
    hl.bind("up", resize_active(0, -10), { repeating = true })
    hl.bind("down", resize_active(0, 10), { repeating = true })
    hl.bind("return", hl.dsp.submap("reset"))
    hl.bind("escape", hl.dsp.submap("reset"))
    -- NB: do not re-bind the enter combo (SUPER+R) inside the submap — in the
    -- Lua API that re-triggers on the same press and exits immediately.
end)

-- Media keys.
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioStop", hl.dsp.exec_cmd("playerctl stop"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"), { locked = true })
hl.bind("XF86AudioMute", hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"), { locked = true })
hl.bind("XF86AudioMicMute", hl.dsp.exec_cmd(scripts .. "/audio.control.sh mic-mute"), { locked = true })

-- Brightness keys.
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd(shared .. "/monitor.brightness.sh increase"), { locked = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd(shared .. "/monitor.brightness.sh decrease"), { locked = true })

-- Lid switch.
hl.bind("switch:Lid Switch", hl.dsp.exec_cmd(scripts .. "/monitor.toggle.sh"), { locked = true })

------------------------------------------------------------- WINDOW RULES
-- xdg-desktop-portal-hyprland Qt share picker.
hl.window_rule({
    name = "hyprland-share-picker",
    match = { class = "^hyprland-share-picker$" },
    float = true,
    size = "500 400",
    move = "monitor_w/2-250 30",
    focus_on_activate = true,
})

-- GTK portal share picker (fallback when GTK portal handles ScreenCast).
hl.window_rule({
    name = "gtk-share-picker",
    match = { title = "^(Select what to share)$" },
    float = true,
    size = "800 600",
    move = "monitor_w/2-400 30",
    focus_on_activate = true,
})

-- Volume control (pavucontrol).
hl.window_rule({
    name = "pavucontrol",
    match = { class = "org\\.pulseaudio\\.pavucontrol" },
    float = true,
    size = "800 600",
    move = "monitor_w/2-400 30",
    focus_on_activate = true,
})

-- Bluetooth manager (blueman).
hl.window_rule({
    name = "blueman-manager",
    match = { class = "\\.blueman-manager-wrapped" },
    float = true,
    size = "800 600",
    move = "monitor_w/2-400 30",
    focus_on_activate = true,
})

-- Network connection editor.
hl.window_rule({
    name = "nm-connection-editor",
    match = { class = "nm-connection-editor" },
    float = true,
    size = "800 600",
    move = "monitor_w/2-400 30",
    focus_on_activate = true,
})

-- JetBrains IDEs: keep focus on popups/dialogs.
hl.window_rule({
    name = "jetbrains-focus",
    match = { class = "^jetbrains-" },
    focus_on_activate = true,
})
hl.window_rule({
    name = "jetbrains-stay-focused",
    match = { class = "^jetbrains-", float = true },
    stay_focused = true,
})

-- JetBrains Toolbox.
hl.window_rule({
    name = "jetbrains-toolbox",
    match = { class = "jetbrains-toolbox" },
    float = true,
    move = "monitor_w-window_w-1 30",
    focus_on_activate = true,
    stay_focused = true,
})

-- VPN prompt terminal.
hl.window_rule({
    name = "vpn-prompt",
    match = { class = "vpn-prompt" },
    float = true,
    size = "640 240",
    move = "monitor_w/2-320 30",
    focus_on_activate = true,
    stay_focused = true,
})

-- Steam.
hl.window_rule({
    name = "steam-float",
    match = { class = "steam" },
    float = true,
})
hl.window_rule({
    name = "steam-main-tile",
    match = { class = "steam", title = "^Steam$" },
    tile = true,
})
hl.window_rule({
    name = "steam-friends-tile",
    match = { class = "steam", title = "^Friends List$" },
    tile = true,
    size = "400 900",
})
