-- Hyprland Lua config (0.55+). Replaces the old sourced .conf files.
-- Dynamic, Nix-derived values (cursor theme, NVIDIA env, hy3 plugin path)
-- live in nix.lua, generated by modules/home/xdg/hypr.nix.
--
-- `hl` is injected by Hyprland at runtime. lua-language-server learns its
-- API from generated stubs (~/.config/hypr/hl.meta.lua + hy3.meta.lua, built
-- by modules/home/xdg/hypr.nix) via the workspace.library in .luarc.json.
--
-- Structure: each section is a named setup_* function; the call list at the
-- bottom is the table of contents.
-- nix.lua (generated by modules/home/xdg/hypr.nix) does its env/plugin side
-- effects and returns Nix-derived values: the Catppuccin palette and the
-- in-tree script paths, both single-sourced from Nix.
local nix = require("nix")
local colors = nix.colors
local paths = nix.paths

local mod = "SUPER"
local scripts = paths.scripts
local shared = paths.shared

----------------------------------------------------------------------- ENV
local function setup_env()
    -- PATH, XDG_DATA_DIRS, XCURSOR_THEME, XCURSOR_SIZE come from Home Manager
    -- session variables / NixOS environment.sessionVariables (cursor mirrored
    -- in nix.lua for non-NixOS session managers).
    for _, e in ipairs({
        { "XDG_CURRENT_DESKTOP", "Hyprland" },
        { "XDG_SESSION_TYPE", "wayland" },
        { "XDG_SESSION_DESKTOP", "Hyprland" },
        { "GDK_BACKEND", "wayland" },
        { "GTK_USE_PORTAL", "0" },
        { "QT_QPA_PLATFORMTHEME", "qt5ct" },
        { "QT_STYLE_OVERRIDE", "kvantum" },
        { "COLOR_SCHEME", "prefer-dark" },
        { "ELECTRON_OZONE_PLATFORM_HINT", "auto" },
        { "MOZ_ENABLE_WAYLAND", "1" },
        { "TERMINAL", "alacritty" },
    }) do
        hl.env(e[1], e[2])
    end
end

------------------------------------------------------------------ MONITORS
-- Single source of truth for monitor rules. Re-applied on every reload and
-- by scripts/monitor.toggle.sh (and the HM reload hook) on dock/lid events
-- via the exposed _G.reflow_monitors.
local monitors = {
    { output = "", mode = "highres", scale = "1" },
    { output = "eDP-1", mode = "preferred", scale = "1.5" },
    { output = "desc:LG Electronics LG HDR WQHD 207NTXRAJ498", mode = "preferred", scale = "1" },
    { output = "desc:LG Electronics LG HDR 4K 0x00016261", mode = "preferred", scale = "1.5" },
}

-- Re-apply every monitor rule in one pass. When lid_closed is true the
-- built-in panel (eDP-1) is disabled *within the same pass* that re-runs
-- `position = "auto"` for the externals, so they pack from 0,0 with the
-- panel already gone. Doing the disable and the auto-positioning together is
-- the whole point: a reload that positions an external to the right of a
-- still-enabled eDP and only disables the panel afterwards strands the
-- external at a half-screen x offset (the "workspace shown offset by half"
-- bug on dock + lid-close), which previously only a manual `hyprctl reload`
-- cleared.
function _G.reflow_monitors(lid_closed)
    for _, m in ipairs(monitors) do
        local rule = { output = m.output, mode = m.mode, position = "auto", scale = m.scale }
        if lid_closed and m.output == "eDP-1" then
            rule.disabled = true
        end
        hl.monitor(rule)
    end
end

local function setup_monitors()
    reflow_monitors(false)
end

-------------------------------------------------------------------- CONFIG
local function setup_config()
    hl.config({
        general = {
            layout = "hy3",
            gaps_workspaces = 0,
            gaps_in = 0,
            gaps_out = 0,
            hover_icon_on_border = false,
            col = {
                inactive_border = colors.crust,
                nogroup_border = colors.crust,
                active_border = colors.mauve,
                nogroup_border_active = colors.mauve,
            },
        },
        dwindle = { preserve_split = true },
        master = { new_status = "slave", orientation = "center" },
        ecosystem = { no_update_news = true, no_donation_nag = true },
        decoration = { blur = { enabled = false } },
        animations = { enabled = false },
        input = {
            repeat_rate = 50,
            repeat_delay = 300,
            force_no_accel = true,
            kb_layout = "us,dk,es",
            kb_options = "grp:toggle",
        },
        misc = {
            disable_hyprland_logo = true,
            disable_splash_rendering = true,
            focus_on_activate = false,
            -- HM activation hook reloads explicitly
            -- (modules/activation/_non-privileged/reload-hyprland.nix) so it can
            -- preserve focused workspace across multi-monitor reload.
            disable_autoreload = true,
        },
        xwayland = { force_zero_scaling = true },
    })
end

-- hy3 plugin config. The plugin is loaded in nix.lua via hl.plugin.load;
-- guard on hl.plugin.hy3 because plugin.* config keys only exist once it has
-- registered, and hl.config errors on unknown keys (per the official example).
local function setup_plugins()
    if hl.plugin.hy3 == nil then
        return
    end
    hl.config({
        plugin = {
            hy3 = {
                node_collapse_policy = 2,
                tabs = {
                    height = 15,
                    padding = 5,
                    render_text = true,
                    text_center = false,
                    text_height = 8,
                    text_padding = 3,
                    colors = {
                        active = colors.mauve,
                        active_text = colors.text,
                        urgent = colors.red,
                        urgent_text = colors.text,
                        inactive = colors.surface0,
                        inactive_text = colors.subtext0,
                    },
                },
                autotile = {
                    enable = true,
                    ephemeral_groups = true,
                    trigger_width = 600,
                    trigger_height = 0,
                    workspaces = "all",
                },
            },
        },
    })
end

-------------------------------------------------------------------- DEVICE
local function setup_device()
    -- Per-device block instead of global input.touchpad{}. Global touchpad
    -- settings sometimes fail to re-apply to the i2c-hid touchpad after
    -- `hyprctl reload` (triggered on dock unplug by scripts/monitor.toggle.sh),
    -- leaving two-finger scroll dead until a Hyprland restart. A device block
    -- fully overrides input.touchpad{} (hyprwm/Hyprland#2895), so scroll options
    -- must be set here or libinput falls back to its own defaults.
    hl.device({
        name = "snsl0028:00-2c2f:0028-touchpad",
        middle_button_emulation = true,
        clickfinger_behavior = true,
        drag_lock = true,
        tap_to_click = true,
        natural_scroll = false,
        scroll_method = "2fg",
        scroll_factor = 1.0,
        disable_while_typing = false,
    })
end

----------------------------------------------------------------- AUTOSTART
local function setup_autostart()
    hl.on("hyprland.start", function()
        for _, cmd in ipairs({
            -- Update D-Bus and systemd environment. QT_QPA_PLATFORMTHEME and
            -- QT_STYLE_OVERRIDE are intentionally NOT imported to systemd to keep
            -- them from persisting and breaking a later KDE Plasma login.
            "dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP GTK_THEME XDG_DATA_DIRS SSH_AUTH_SOCK HYPRLAND_INSTANCE_SIGNATURE",
            "compositor-session hyprland",
            "hyprctl setcursor $XCURSOR_THEME $XCURSOR_SIZE",
            "hypridle",
            -- Bare daemon opens the IPC socket; the hyprsunset-sun systemd user
            -- service then sets its temperature on the real sunrise/sunset
            -- schedule (hyprsunset has no native lat/long mode). The wayle
            -- widget reads/overrides the same socket via that service.
            "hyprsunset",
            "wl-paste --watch cliphist store",
            "wl-clip-persist --clipboard regular",
            -- No nm-applet/blueman-applet: wayle's native network + bluetooth
            -- modules replace those tray icons.
            scripts .. "/hy3.tiling.sh",
            scripts .. "/monitor.toggle.sh daemon",
            -- Toast the active keyboard layout on each grp:toggle switch (xkb
            -- toggles internally — no keybind to hook; listen to socket2).
            "wayle-widget kb-toast hypr",
        }) do
            hl.exec_cmd(cmd)
        end
    end)
end

----------------------------------------------------------- WINDOW EVENTS
local function setup_window_events()
    -- JetBrains floating popups sometimes open mis-sized; nudge the height
    -- +1px then back to force a redraw (replaces jetbrains.popup.resize.sh,
    -- which did the same over the .socket2.sock event stream).
    hl.on("window.open", function(w)
        if not w or not w.floating then return end
        if not (w.class and w.class:match("^jetbrains%-")) then return end
        local s = w.size
        hl.dispatch(hl.dsp.window.resize({ x = s.x, y = s.y + 1, window = w }))
        hl.dispatch(hl.dsp.window.resize({ x = s.x, y = s.y, window = w }))
    end)
end

--------------------------------------------------------- KEYBIND HELPERS
-- hy3 is the only layout. These dispatch hy3's custom commands; they access
-- hl.plugin.hy3 at keypress time (the plugin is loaded by then) to avoid any
-- config-eval ordering races. resize_active uses the native dispatcher.
local function hy3_focus(d)
    return function() hl.dispatch(hl.plugin.hy3.move_focus(d)) end
end

-- Move the focused window, but skip the dispatch if it is already at the
-- workspace edge in that direction: hy3:movewindow at an edge collapses/creates
-- a group and shifts sizes by group_inset, shrinking a neighbour (the old
-- wrapper.movewindow.sh guarded the same way).
local function hy3_move(d)
    return function()
        local f = hl.get_active_window()
        if not f then return end
        local axis = (d == "l" or d == "r") and "x" or "y"
        local toward_max = (d == "r" or d == "d")
        local at_edge = true
        for _, w in ipairs(hl.get_workspace_windows(f.workspace)) do
            local beyond
            if toward_max then
                beyond = w.at[axis] > f.at[axis]
            else
                beyond = w.at[axis] < f.at[axis]
            end
            if beyond then
                at_edge = false
                break
            end
        end
        if not at_edge then hl.dispatch(hl.plugin.hy3.move_window(d)) end
    end
end

local function hy3_to_ws(n)
    return function() hl.dispatch(hl.plugin.hy3.move_to_workspace(tostring(n))) end
end

local function hy3_kill()
    hl.dispatch(hl.plugin.hy3.kill_active())
end

local function resize_active(dx, dy)
    return hl.dsp.window.resize({ x = dx, y = dy, relative = true })
end

----------------------------------------------------------------- KEYBINDS
local function setup_keybinds()
    -- Launchers.
    hl.bind(mod .. " + RETURN", hl.dsp.exec_cmd("alacritty"))
    hl.bind(mod .. " + SHIFT + E", hl.dsp.exec_cmd("pcmanfm"))
    hl.bind(mod .. " + SPACE", hl.dsp.exec_cmd("rofi -drun-reload-desktop-cache -drun-use-desktop-cache -show drun -location 0 -width 60"))
    hl.bind(mod .. " + SHIFT + SPACE", hl.dsp.exec_cmd([[rofi -show combi -combi-modes "run" -modes combi -run-command "]] .. scripts .. [[/rofi.run.sh {cmd}" -location 0 -width 60]]))
    hl.bind(mod .. " + CTRL + SPACE", hl.dsp.exec_cmd([[rofi -show combi -combi-modes "window" -modes combi]]))
    hl.bind("SHIFT + Print", hl.dsp.exec_cmd("screenshot output"))
    hl.bind("Print", hl.dsp.exec_cmd("screenshot region"))
    hl.bind(mod .. " + SHIFT + R", hl.dsp.exec_cmd("screen-record toggle"))
    hl.bind(mod .. " + V", hl.dsp.exec_cmd([[cliphist list | rofi -dmenu | cliphist decode | wl-copy && wtype -M ctrl v && notify-send "Pasted selection"]]))
    hl.bind(mod .. " + C", hl.dsp.exec_cmd([[wl-copy "$(wl-paste -p)" && notify-send "Copied selection"]]))
    hl.bind(mod .. " + M", hl.dsp.exec_cmd("mail-open"))

    -- Window management.
    hl.bind(mod .. " + SHIFT + Q", hy3_kill)
    hl.bind(mod .. " + F", hl.dsp.window.fullscreen())
    hl.bind(mod .. " + T", hl.dsp.window.float({ action = "toggle" }))
    hl.bind(mod .. " + escape", hl.dsp.exec_cmd(shared .. "/hyprlock.launch.sh"))
    hl.bind(mod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
    hl.bind(mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })
    hl.bind(mod .. " + delete", hl.dsp.exit())

    -- Directional focus (arrows) + move (SHIFT) + resize (CTRL).
    local resize_step = { left = { -50, 0 }, right = { 50, 0 }, up = { 0, -50 }, down = { 0, 50 } }
    for key, d in pairs({ left = "l", right = "r", up = "u", down = "d" }) do
        hl.bind(mod .. " + " .. key, hy3_focus(d))
        hl.bind(mod .. " + SHIFT + " .. key, hy3_move(d))
        hl.bind(mod .. " + CTRL + " .. key, resize_active(resize_step[key][1], resize_step[key][2]))
    end

    -- Focus cycling (mouse wheel + brackets).
    for key, d in pairs({ mouse_down = "r", bracketright = "r", mouse_up = "l", bracketleft = "l" }) do
        hl.bind(mod .. " + " .. key, hy3_focus(d))
    end

    -- Relative workspace switching (native, layout-independent).
    for combo, ws in pairs({
        ["SHIFT + mouse_down"] = "e+1",
        ["SHIFT + mouse_up"] = "e-1",
        ["SHIFT + bracketright"] = "e+1",
        ["SHIFT + bracketleft"] = "e-1",
        ["Tab"] = "e+1",
        ["SHIFT + Tab"] = "e-1",
    }) do
        hl.bind(mod .. " + " .. combo, hl.dsp.focus({ workspace = ws }))
    end

    -- Workspace switch (native) + move-active-to-workspace (hy3).
    for i = 1, 10 do
        local key = i % 10
        hl.bind(mod .. " + " .. key, hl.dsp.focus({ workspace = i }))
        hl.bind(mod .. " + SHIFT + " .. key, hy3_to_ws(i))
    end

    -- Resize submap. NB: do not re-bind the enter combo (SUPER+R) inside the
    -- submap — in the Lua API that re-triggers on the same press and exits at once.
    --
    -- The hl Lua submap is NOT a native Hyprland submap (hyprctl submap stays
    -- "default"), so the wayle bar can't observe it. Enter/exit therefore write
    -- and remove a tmpfs marker ($XDG_RUNTIME_DIR/wayle-submap, cleared on
    -- reboot) that the bar's custom "submap" module watches.
    local submap_marker = '"$XDG_RUNTIME_DIR/wayle-submap"'
    local function enter_submap(name)
        return function()
            hl.dispatch(hl.dsp.exec_cmd("printf %s " .. name .. " > " .. submap_marker))
            hl.dispatch(hl.dsp.submap(name))
        end
    end
    local function exit_submap()
        hl.dispatch(hl.dsp.exec_cmd("rm -f " .. submap_marker))
        hl.dispatch(hl.dsp.submap("reset"))
    end
    hl.bind(mod .. " + R", enter_submap("resize_mode"))
    hl.define_submap("resize_mode", function()
        for key, step in pairs({ right = { 10, 0 }, left = { -10, 0 }, up = { 0, -10 }, down = { 0, 10 } }) do
            hl.bind(key, resize_active(step[1], step[2]), { repeating = true })
        end
        hl.bind("return", exit_submap)
        hl.bind("escape", exit_submap)
    end)

    -- Media + brightness keys: all run on the lock screen too ({ locked }).
    -- The laptop lid is NOT bound here: since the hyprland 0.55 / aquamarine
    -- 0.11 bump the `switch:Lid Switch` SWITCH_TOGGLE never reaches Hyprland's
    -- keybind manager, so the bind is dead. scripts/monitor.toggle.sh's daemon
    -- reads the lid from libinput directly instead (see listen_lid there).
    for _, b in ipairs({
        { "XF86AudioPlay", "playerctl play-pause" },
        { "XF86AudioStop", "playerctl stop" },
        { "XF86AudioPrev", "playerctl previous" },
        { "XF86AudioNext", "playerctl next" },
        { "XF86AudioRaiseVolume", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+" },
        { "XF86AudioLowerVolume", "wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-" },
        { "XF86AudioMute", "wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle" },
        { "XF86AudioMicMute", "wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle" },
        { "XF86MonBrightnessUp", shared .. "/monitor.brightness.sh increase" },
        { "XF86MonBrightnessDown", shared .. "/monitor.brightness.sh decrease" },
    }) do
        hl.bind(b[1], hl.dsp.exec_cmd(b[2]), { locked = true })
    end
end

------------------------------------------------------------- WINDOW RULES
-- Floating, horizontally centered near the top, focused on activate. `extra`
-- merges in any additional rule fields (e.g. stay_focused).
local function float_centered(name, match, w, h, extra)
    local rule = {
        name = name,
        match = match,
        float = true,
        focus_on_activate = true,
        size = w .. " " .. h,
        move = "monitor_w/2-" .. math.floor(w / 2) .. " 30",
    }
    for k, v in pairs(extra or {}) do
        rule[k] = v
    end
    hl.window_rule(rule)
end

local function setup_window_rules()
    float_centered("vpn-prompt", { class = "vpn-prompt" }, 640, 240, { stay_focused = true })

    -- JetBrains IDEs: keep focus on popups/dialogs.
    hl.window_rule({
        name = "jetbrains-focus",
        match = { class = "^jetbrains-" },
        focus_on_activate = true,
    })
    hl.window_rule({
        name = "jetbrains-stay-focused",
        match = { class = "^jetbrains-", float = true },
        stay_focused = true,
    })

    -- JetBrains Toolbox (top-right corner).
    hl.window_rule({
        name = "jetbrains-toolbox",
        match = { class = "jetbrains-toolbox" },
        float = true,
        move = "monitor_w-window_w-1 30",
        focus_on_activate = true,
        stay_focused = true,
    })

    -- Steam: float by default, but tile the main window and friends list.
    hl.window_rule({ name = "steam-float", match = { class = "steam" }, float = true })
    hl.window_rule({ name = "steam-main-tile", match = { class = "steam", title = "^Steam$" }, tile = true })
    hl.window_rule({ name = "steam-friends-tile", match = { class = "steam", title = "^Friends List$" }, tile = true, size = "400 900" })
end

--------------------------------------------------------------------- MAIN
setup_env()
setup_monitors()
setup_config()
setup_plugins()
setup_device()
setup_autostart()
setup_window_events()
setup_keybinds()
setup_window_rules()
