# Unlike claude/codex, crush's config file can be a read-only store symlink:
# every write crush makes itself (model selection, onboarding, docker MCP) goes
# to ScopeGlobal, which is ~/.local/share/crush/crush.json -- a different file,
# and one loaded AFTER this one, so an in-app model switch still wins.
_: {
  flake.modules.homeManager.crush =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    lib.mkIf config.features.crush (
      let
        c = pkgs.stubbe.withHash;

        # crush 0.92 hardcodes two themes (Charmtone Pantera and a Hypercrush
        # variant that just delegates to it), picks between them by PROVIDER id,
        # and exposes no theme option -- so a palette has to be compiled in.
        # Adding a file to the styles package keeps that to one substitution in
        # themes.go; rewriting the charmtone literal in place would be ~35, plus
        # dropping the then-unused import.
        #
        # Roles are mapped from how quickstyle.go consumes them, not from their
        # names: `successMostSubtle` is the UI's main accent (prompt, focused
        # borders, links, diff additions) and `onPrimary` is the foreground laid
        # over primary/secondary/status backgrounds, so it has to be dark
        # against Catppuccin's pastels. The ANSI block mirrors the terminal
        # palette in modules/terminal.nix, so `!`-mode shell output looks the
        # same inside crush as outside it.
        catppuccinMocha = pkgs.writeText "catppuccin.go" ''
          // Generated by modules/ai/crush.nix. Indented with spaces, not gofmt'd.
          package styles

          import "charm.land/lipgloss/v2"

          // CatppuccinMocha returns the Catppuccin Mocha theme.
          func CatppuccinMocha() Styles {
              s := quickStyle(quickStyleOpts{
                  primary:   lipgloss.Color("${c.mauve}"),
                  secondary: lipgloss.Color("${c.pink}"),
                  accent:    lipgloss.Color("${c.lavender}"),
                  keyword:   lipgloss.Color("${c.mauve}"),

                  fgBase:       lipgloss.Color("${c.text}"),
                  fgSubtle:     lipgloss.Color("${c.subtext0}"),
                  fgMoreSubtle: lipgloss.Color("${c.overlay1}"),
                  fgMostSubtle: lipgloss.Color("${c.overlay0}"),

                  onPrimary: lipgloss.Color("${c.crust}"),

                  bgBase:         lipgloss.Color("${c.base}"),
                  bgLeastVisible: lipgloss.Color("${c.mantle}"),
                  bgLessVisible:  lipgloss.Color("${c.surface0}"),
                  bgMostVisible:  lipgloss.Color("${c.surface2}"),

                  separator: lipgloss.Color("${c.surface0}"),

                  destructive:       lipgloss.Color("${c.maroon}"),
                  error:             lipgloss.Color("${c.red}"),
                  warningSubtle:     lipgloss.Color("${c.yellow}"),
                  warning:           lipgloss.Color("${c.peach}"),
                  attention:         lipgloss.Color("${c.peach}"),
                  busy:              lipgloss.Color("${c.yellow}"),
                  info:              lipgloss.Color("${c.blue}"),
                  infoMoreSubtle:    lipgloss.Color("${c.sapphire}"),
                  infoMostSubtle:    lipgloss.Color("${c.sky}"),
                  success:           lipgloss.Color("${c.teal}"),
                  successMoreSubtle: lipgloss.Color("${c.teal}"),
                  successMostSubtle: lipgloss.Color("${c.green}"),

                  ansiBlack:   lipgloss.Color("${c.surface1}"),
                  ansiRed:     lipgloss.Color("${c.red}"),
                  ansiGreen:   lipgloss.Color("${c.green}"),
                  ansiYellow:  lipgloss.Color("${c.yellow}"),
                  ansiBlue:    lipgloss.Color("${c.blue}"),
                  ansiMagenta: lipgloss.Color("${c.pink}"),
                  ansiCyan:    lipgloss.Color("${c.teal}"),
                  ansiWhite:   lipgloss.Color("${c.subtext1}"),

                  ansiBrightBlack:   lipgloss.Color("${c.surface2}"),
                  ansiBrightRed:     lipgloss.Color("${c.red}"),
                  ansiBrightGreen:   lipgloss.Color("${c.green}"),
                  ansiBrightYellow:  lipgloss.Color("${c.yellow}"),
                  ansiBrightBlue:    lipgloss.Color("${c.blue}"),
                  ansiBrightMagenta: lipgloss.Color("${c.pink}"),
                  ansiBrightCyan:    lipgloss.Color("${c.teal}"),
                  ansiBrightWhite:   lipgloss.Color("${c.subtext0}"),
              })

              // The bang (!) shell prompt and shell bar are set outside
              // quickStyle upstream too, so they need restating here.
              s.Editor.PromptBangIconFocused = s.Editor.PromptBangIconFocused.
                  Foreground(lipgloss.Color("${c.crust}")).
                  Background(lipgloss.Color("${c.mauve}"))
              s.Editor.PromptBangDotsFocused = s.Editor.PromptBangDotsFocused.
                  Foreground(lipgloss.Color("${c.mauve}"))
              s.Editor.PromptBangDotsBlurred = s.Editor.PromptBangDotsBlurred.
                  Foreground(lipgloss.Color("${c.overlay0}"))

              s.Messages.ShellBarFocused = s.Messages.ShellBarFocused.
                  BorderForeground(lipgloss.Color("${c.mauve}"))
              s.Messages.ShellBarBlurred = s.Messages.ShellBarBlurred.
                  BorderForeground(lipgloss.Color("${c.surface1}"))
              s.Messages.ShellPrompt = s.Messages.ShellPrompt.
                  Foreground(lipgloss.Color("${c.mauve}"))
              s.Messages.ShellPromptBlurred = s.Messages.ShellPromptBlurred.
                  Foreground(lipgloss.Color("${c.overlay1}"))

              return s
          }
        '';

        # Nothing here pins a version or a hash: src AND vendorHash both come
        # from the nixpkgs pin, so `nix flake update` is what moves crush, and
        # it lands on whatever release tag nixpkgs is carrying. Patching Go
        # source does not touch the module set, which is why postPatch alone
        # needs no vendorHash of our own -- building a rev nixpkgs does not
        # package would, since fetching Go modules is a fixed-output derivation.
        #
        # Four UI decisions upstream exposes no knob for. Every --replace-fail is
        # load-bearing: it fails the build loudly if upstream moves the line,
        # rather than silently dropping the change.
        # Tests of the thinking box all assert that it renders, so the reasoning
        # patch below makes them moot. Appended to nixpkgs' own -skip regex
        # rather than replacing checkFlags, which would drop its skips for the
        # tests that fail in the sandbox. Go honours one -skip only, so a second
        # flag would shadow theirs. Every TestThinkingWindow_ case is affected;
        # TestAssistantSectionCache_ has six more that still pass (content and
        # error caching), so its four are named instead of skipped by prefix.
        thinkingTests = [
          "^TestThinkingWindow_"
          "^TestAssistantSectionCache_ContentChangeDoesNotInvalidateThinking$"
          "^TestAssistantSectionCache_ResizeInvalidatesAll$"
          "^TestAssistantSectionCache_ThinkingBoxHeightSurvivesCacheHit$"
          "^TestAssistantSectionCache_ThinkingChangeDoesNotInvalidateContent$"
        ];

        crush = pkgs.crush.overrideAttrs (old: {
          checkFlags = map (
            flag:
            if lib.hasPrefix "-skip=" flag then "${flag}|${lib.concatStringsSep "|" thinkingTests}" else flag
          ) old.checkFlags;

          postPatch = (old.postPatch or "") + ''
            cp ${catppuccinMocha} internal/ui/styles/catppuccin.go
            # Both hits are in themes.go (the provider switch and the Hypercrush
            # delegate), so every provider lands on the same palette.
            substituteInPlace internal/ui/styles/themes.go \
              --replace-fail 'return CharmtonePantera()' 'return CatppuccinMocha()'

            # 3 rows is only the FLOOR upstream picked: the textarea is already
            # DynamicHeight and grows to fit, up to 15 rows. Moving the floor to
            # 1 leaves shift+enter growing the prompt exactly as before.
            substituteInPlace internal/ui/model/ui.go \
              --replace-fail 'const TextareaMinHeight = 3' 'const TextareaMinHeight = 1'

            # The "Crush update available" toast fires unconditionally at
            # startup, and nixpkgs is normally a release behind, so it shows up
            # on most launches with nothing actionable behind it.
            substituteInPlace internal/app/app.go \
              --replace-fail 'go app.checkForUpdates(ctx)' '// update check disabled: the version follows the nixpkgs pin'

            # Drop the reasoning block from the transcript. Zeroing the two
            # `thinking` locals is enough: every branch that renders the box,
            # its footer, the F5 tail window and the blank separator is gated on
            # them, and ShouldRenderAssistantMessage stops keeping a
            # thinking-only message alive as an empty bubble. Reasoning is still
            # requested, streamed and stored -- only the render is suppressed.
            substituteInPlace internal/ui/chat/assistant.go \
              --replace-fail 'thinking := strings.TrimSpace(a.message.ReasoningContent().Thinking)' 'thinking := ""'
            substituteInPlace internal/ui/chat/messages.go \
              --replace-fail 'thinking := strings.TrimSpace(msg.ReasoningContent().Thinking)' 'thinking := ""'
          '';
        });
      in
      {
        home.packages = [ crush ];

        sops.secrets.z-ai-token = pkgs.stubbe.secret { name = "z-ai-token"; };

        xdg.configFile."crush/crush.json".source = pkgs.stubbe.gen.json "crush.json" {
          "$schema" = "https://charm.land/crush.json";

          # Only the credential is ours: catwalk's built-in `zai` provider
          # carries the endpoint and the model list, and a user entry under the
          # same id overrides field by field instead of replacing it. The token
          # stays out of the world-readable store because crush expands config
          # values through its embedded shell, so $(...) runs at load time.
          providers.zai.api_key = "$(cat ${config.sops.secrets.z-ai-token.path})";

          # Deliberately no `models` block: crush resolves catwalk's default
          # large/small pair on first run and persists it to the data config, so
          # switching model in-app sticks instead of being reverted next start.

          mcp = config.stubbe.mcp.clients.crush;

          # `crush --yolo` is a flag on the ROOT command only, so baking it into
          # a wrapper would make `crush run`/`crush logs` die with "unknown
          # flag". allowed_tools is the config-level equivalent and applies to
          # both the TUI and `crush run`. MCP tool calls never reach the
          # permission service at all, so this list only needs crush's own tools
          # -- mirrored from allToolNames() in internal/config/config.go. A tool
          # added upstream after this list simply prompts once.
          permissions.allowed_tools = [
            "agent"
            "bash"
            "crush_info"
            "crush_logs"
            "job_output"
            "job_kill"
            "download"
            "edit"
            "multiedit"
            "lsp_diagnostics"
            "lsp_references"
            "lsp_restart"
            "lsp_symbols"
            "lsp_definition"
            "lsp_call_hierarchy"
            "lsp_rename"
            "lsp_replace_symbol"
            "fetch"
            "agentic_fetch"
            "glob"
            "grep"
            "ls"
            "question"
            "sourcegraph"
            "todos"
            "view"
            "write"
            "list_mcp_resources"
            "read_mcp_resource"
          ];

          options = {
            tui = {
              # The sidebar is nearly all of crush's chrome -- logo, session
              # title, cwd, model card, changed-file list, LSP/MCP/skills panels
              # -- and compact_mode is what drops it. Below 120 columns crush
              # forces this on anyway, so the wide layout was never the default.
              compact_mode = true;
              # Split view spends half the width on the pre-image; unified reads
              # like `git diff` and survives a narrow window.
              diff_mode = "unified";
              scrollbar = "never";
              # Leaves view.BackgroundColor unset, so the terminal's own
              # background (and its opacity) shows through instead of crush
              # painting bgBase over the whole screen. Widget backgrounds still
              # paint, but they are the same Catppuccin surfaces the terminal
              # uses, so the seams do not show.
              transparent = true;
            };

            disable_metrics = true;

            # Matches includeCoAuthoredBy = false for Claude Code: no trailer,
            # no "Generated with Crush" line in commits or PR bodies.
            attribution = {
              trailer_style = "none";
              generated_with = false;
            };
          };
        };
      }
    );
}
