general.live_config_reload = true

general.import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[window]
decorations = "none"
startup_mode = "Maximized"
dynamic_title = true
dynamic_padding = true

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[scrolling]
history = 0

[font]
size = 12

[font.normal]
family = "JetBrains Mono Nerd Font"
style = "Regular"

[font.bold]
family = "JetBrains Mono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrains Mono Nerd Font"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[bell]
animation = "EaseOutExpo"
duration = 0

[mouse]
hide_when_typing = true
bindings = [{ mouse = "Middle", action = "PasteSelection" }]

[cursor]
style = "Block"
unfocused_hollow = true

[keyboard]
bindings = [
  { key = "PageUp", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "PageDown", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "Home", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "End", mods = "Shift", mode = "~Alt", action = "ReceiveChar" },
  { key = "K", mods = "Command", mode = "~Vi|~Search", action = "ReceiveChar" },
  { key = "F", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
  { key = "F", mods = "Command", mode = "~Search", action = "ReceiveChar" },
  { key = "B", mods = "Control|Shift", mode = "~Search", action = "ReceiveChar" },
  { key = "B", mods = "Command", mode = "~Search", action = "ReceiveChar" },
  { key = "Paste", action = "ReceiveChar" },
  { key = "Copy", action = "ReceiveChar" },
  # { key = "V", mods = "Control|Shift", mode = "~Vi", action = "ReceiveChar" },
  { key = "V", mods = "Command", action = "ReceiveChar" },
  # { key = "C", mods = "Control|Shift", action = "ReceiveChar" },
  { key = "C", mods = "Command", action = "ReceiveChar" },
  # { key = "C", mods = "Control|Shift", mode = "Vi|~Search", action = "ReceiveChar" },
  { key = "C", mods = "Command", mode = "Vi|~Search", action = "ReceiveChar" },
  { key = "Insert", mods = "Shift", action = "ReceiveChar" },
]

[selection]
save_to_clipboard = false
